name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: macos-latest
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: 'recursive'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Preconfigure CMake without i8mm
        run: |
          rm -rf whisper.cpp/build_go
          cmake -S whisper.cpp -B whisper.cpp/build_go \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_C_FLAGS="-march=armv8.5-a" \
            -DCMAKE_CXX_FLAGS="-march=armv8.5-a" \
            -DGGML_NATIVE=OFF || true
      - name: Build whisper.cpp bindings
        run: make -C whisper.cpp/bindings/go
      - name: Semantic Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run GoReleaser
        if: steps.semantic.outputs.new_release_published == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
