name: Test Whisper.cpp Build

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Attempt to build whisper.cpp bindings
        run: make -C whisper.cpp/bindings/go CMAKE_C_FLAGS="-DWHISPER_NO_I8MM=1"
